name: Build

on:
  push:
    branches: 'main'
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        hugo-version: [
            0.123.2,
            0.123.1,
            0.123.0,
            0.122.0,
            0.121.2
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build image
        uses: docker/bake-action@v4
        env:
          VERSION: ${{ matrix.hugo-version }}
        with:
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
          push: true
