name: Renovate

on:
  push:
    branches: 'renovate/**'

permissions:
  contents: read
  packages: read

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build image
        uses: docker/bake-action@v4
        with:
          set: |
            *.cache-from=type=gha
